//
//  TypeInfoTable.m
//  TestApp
//
//  Created by WooKyoung Noh on 13/02/11.
//  Copyright 2011 factorcat. All rights reserved.
//

#import "TypeInfoTable.h"
#import "NSDictionaryExt.h"
#import "NSStringExt.h"

@implementation TypeInfoTable
@synthesize typedefTable;
@synthesize propertyTable;


-(NSString*) objectDescription:(id)obj targetClass:(NSString*)targetClass propertyName:(NSString*)propertyName {
	NSString* typeKey = SWF(@"%@ %@", targetClass, propertyName);
	NSString* typeName = [propertyTable objectForKey:typeKey];
	if (nil != typeName) {
		if ([typedefTable hasKey:typeName]) {
			NSArray* enumValues = [typedefTable objectForKey:typeName];
			int idx = [obj intValue];
			NSString* value = [enumValues objectAtIndex:idx];
			return SWF(@"%d %@", idx, value);
		} else if ([@"BOOL" isEqualToString:typeName]) {
			BOOL value = [obj boolValue];
			return SWF(@"%@", value ? @"true" : @"false");
		} else if ([@"CGRect" isEqualToString:typeName]) {
		} else if ([@"CGSize" isEqualToString:typeName]) {
		} else if ([@"CGPoint" isEqualToString:typeName]) {
		}
	}
	return SWF(@"%@", obj);
}


//GEN
-(void) load_typedef_table {
	self.typedefTable = [NSDictionary dictionaryWithKeysAndObjects: 
		@"UIAccessibilityScrollDirection", _w(@"UIAccessibilityScrollDirectionRight UIAccessibilityScrollDirectionLeft UIAccessibilityScrollDirectionUp UIAccessibilityScrollDirectionDown"),
		@"UIActionSheetStyle", _w(@"UIActionSheetStyleDefault UIActionSheetStyleBlackTranslucent UIActionSheetStyleBlackOpaque"),
		@"UIActivityIndicatorViewStyle", _w(@"UIActivityIndicatorViewStyleWhiteLarge UIActivityIndicatorViewStyleWhite UIActivityIndicatorViewStyleGray"),
		@"UIApplicationState", _w(@"UIApplicationStateActive UIApplicationStateInactive UIApplicationStateBackground"),
		@"UIBarButtonItemStyle", _w(@"UIBarButtonItemStylePlain UIBarButtonItemStyleBordered UIBarButtonItemStyleDone"),
		@"UIBarButtonSystemItem", _w(@"UIBarButtonSystemItemDone UIBarButtonSystemItemCancel UIBarButtonSystemItemEdit UIBarButtonSystemItemSave UIBarButtonSystemItemAdd UIBarButtonSystemItemFlexibleSpace UIBarButtonSystemItemFixedSpace UIBarButtonSystemItemCompose UIBarButtonSystemItemReply UIBarButtonSystemItemAction UIBarButtonSystemItemOrganize UIBarButtonSystemItemBookmarks UIBarButtonSystemItemSearch UIBarButtonSystemItemRefresh UIBarButtonSystemItemStop UIBarButtonSystemItemCamera UIBarButtonSystemItemTrash UIBarButtonSystemItemPlay UIBarButtonSystemItemPause UIBarButtonSystemItemRewind UIBarButtonSystemItemFastForward UIBarButtonSystemItemUndo UIBarButtonSystemItemRedo UIBarButtonSystemItemPageCurl"),
		@"UIBarStyle", _w(@"UIBarStyleDefault UIBarStyleBlack UIBarStyleBlackOpaque UIBarStyleBlackTranslucent"),
		@"UIBaselineAdjustment", _w(@"UIBaselineAdjustmentAlignBaselines UIBaselineAdjustmentAlignCenters UIBaselineAdjustmentNone"),
		@"UIButtonType", _w(@"UIButtonTypeCustom UIButtonTypeRoundedRect UIButtonTypeDetailDisclosure UIButtonTypeInfoLight UIButtonTypeInfoDark UIButtonTypeContactAdd"),
		@"UIControlContentHorizontalAlignment", _w(@"UIControlContentHorizontalAlignmentCenter UIControlContentHorizontalAlignmentLeft UIControlContentHorizontalAlignmentRight UIControlContentHorizontalAlignmentFill"),
		@"UIControlContentVerticalAlignment", _w(@"UIControlContentVerticalAlignmentCenter UIControlContentVerticalAlignmentTop UIControlContentVerticalAlignmentBottom UIControlContentVerticalAlignmentFill"),
		@"UIDatePickerMode", _w(@"UIDatePickerModeTime UIDatePickerModeDate UIDatePickerModeDateAndTime UIDatePickerModeCountDownTimer"),
		@"UIDeviceBatteryState", _w(@"UIDeviceBatteryStateUnknown UIDeviceBatteryStateUnplugged UIDeviceBatteryStateCharging UIDeviceBatteryStateFull"),
		@"UIDeviceOrientation", _w(@"UIDeviceOrientationUnknown UIDeviceOrientationPortrait UIDeviceOrientationPortraitUpsideDown UIDeviceOrientationLandscapeLeft UIDeviceOrientationLandscapeRight UIDeviceOrientationFaceUp UIDeviceOrientationFaceDown"),
		@"UIEventSubtype", _w(@"UIEventSubtypeNone UIEventSubtypeMotionShake UIEventSubtypeRemoteControlPlay UIEventSubtypeRemoteControlPause UIEventSubtypeRemoteControlStop UIEventSubtypeRemoteControlTogglePlayPause UIEventSubtypeRemoteControlNextTrack UIEventSubtypeRemoteControlPreviousTrack UIEventSubtypeRemoteControlBeginSeekingBackward UIEventSubtypeRemoteControlEndSeekingBackward UIEventSubtypeRemoteControlBeginSeekingForward UIEventSubtypeRemoteControlEndSeekingForward"),
		@"UIEventType", _w(@"UIEventTypeTouches UIEventTypeMotion UIEventTypeRemoteControl"),
		@"UIGestureRecognizerState", _w(@"UIGestureRecognizerStatePossible UIGestureRecognizerStateBegan UIGestureRecognizerStateChanged UIGestureRecognizerStateEnded UIGestureRecognizerStateCancelled UIGestureRecognizerStateFailed UIGestureRecognizerStateRecognized"),
		@"UIImageOrientation", _w(@"UIImageOrientationUp UIImageOrientationDown UIImageOrientationLeft UIImageOrientationRight UIImageOrientationUpMirrored UIImageOrientationDownMirrored UIImageOrientationLeftMirrored UIImageOrientationRightMirrored"),
		@"UIInterfaceOrientation", _w(@"UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"),
		@"UIKeyboardAppearance", _w(@"UIKeyboardAppearanceDefault UIKeyboardAppearanceAlert"),
		@"UIKeyboardType", _w(@"UIKeyboardTypeDefault UIKeyboardTypeASCIICapable UIKeyboardTypeNumbersAndPunctuation UIKeyboardTypeURL UIKeyboardTypeNumberPad UIKeyboardTypePhonePad UIKeyboardTypeNamePhonePad UIKeyboardTypeEmailAddress UIKeyboardTypeDecimalPad UIKeyboardTypeAlphabet"),
		@"UILineBreakMode", _w(@"UILineBreakModeWordWrap UILineBreakModeCharacterWrap UILineBreakModeClip UILineBreakModeHeadTruncation UILineBreakModeTailTruncation UILineBreakModeMiddleTruncation"),
		@"UIMenuControllerArrowDirection", _w(@"UIMenuControllerArrowDefault UIMenuControllerArrowUp UIMenuControllerArrowDown UIMenuControllerArrowLeft UIMenuControllerArrowRight"),
		@"UIModalPresentationStyle", _w(@"UIModalPresentationFullScreen UIModalPresentationPageSheet UIModalPresentationFormSheet UIModalPresentationCurrentContext"),
		@"UIModalTransitionStyle", _w(@"UIModalTransitionStyleCoverVertical UIModalTransitionStyleFlipHorizontal UIModalTransitionStyleCrossDissolve UIModalTransitionStylePartialCurl"),
		@"UIPrintInfoDuplex", _w(@"UIPrintInfoDuplexNone UIPrintInfoDuplexLongEdge UIPrintInfoDuplexShortEdge"),
		@"UIPrintInfoOrientation", _w(@"UIPrintInfoOrientationPortrait UIPrintInfoOrientationLandscape"),
		@"UIPrintInfoOutputType", _w(@"UIPrintInfoOutputGeneral UIPrintInfoOutputPhoto UIPrintInfoOutputGrayscale"),
		@"UIProgressViewStyle", _w(@"UIProgressViewStyleDefault UIProgressViewStyleBar"),
		@"UIRemoteNotificationType", _w(@"UIRemoteNotificationTypeNone UIRemoteNotificationTypeBadge UIRemoteNotificationTypeSound UIRemoteNotificationTypeAlert"),
		@"UIReturnKeyType", _w(@"UIReturnKeyDefault UIReturnKeyGo UIReturnKeyGoogle UIReturnKeyJoin UIReturnKeyNext UIReturnKeyRoute UIReturnKeySearch UIReturnKeySend UIReturnKeyYahoo UIReturnKeyDone UIReturnKeyEmergencyCall"),
		@"UIScrollViewIndicatorStyle", _w(@"UIScrollViewIndicatorStyleDefault UIScrollViewIndicatorStyleBlack UIScrollViewIndicatorStyleWhite"),
		@"UISegmentedControlStyle", _w(@"UISegmentedControlStylePlain UISegmentedControlStyleBordered UISegmentedControlStyleBar UISegmentedControlStyleBezeled"),
		@"UIStatusBarAnimation", _w(@"UIStatusBarAnimationNone UIStatusBarAnimationFade UIStatusBarAnimationSlide"),
		@"UIStatusBarStyle", _w(@"UIStatusBarStyleDefault UIStatusBarStyleBlackTranslucent UIStatusBarStyleBlackOpaque"),
		@"UISwipeGestureRecognizerDirection", _w(@"UISwipeGestureRecognizerDirectionRight UISwipeGestureRecognizerDirectionLeft UISwipeGestureRecognizerDirectionUp UISwipeGestureRecognizerDirectionDown"),
		@"UITabBarSystemItem", _w(@"UITabBarSystemItemMore UITabBarSystemItemFavorites UITabBarSystemItemFeatured UITabBarSystemItemTopRated UITabBarSystemItemRecents UITabBarSystemItemContacts UITabBarSystemItemHistory UITabBarSystemItemBookmarks UITabBarSystemItemSearch UITabBarSystemItemDownloads UITabBarSystemItemMostRecent UITabBarSystemItemMostViewed"),
		@"UITableViewCellAccessoryType", _w(@"UITableViewCellAccessoryNone UITableViewCellAccessoryDisclosureIndicator UITableViewCellAccessoryDetailDisclosureButton UITableViewCellAccessoryCheckmark"),
		@"UITableViewCellEditingStyle", _w(@"UITableViewCellEditingStyleNone UITableViewCellEditingStyleDelete UITableViewCellEditingStyleInsert"),
		@"UITableViewCellSelectionStyle", _w(@"UITableViewCellSelectionStyleNone UITableViewCellSelectionStyleBlue UITableViewCellSelectionStyleGray"),
		@"UITableViewCellSeparatorStyle", _w(@"UITableViewCellSeparatorStyleNone UITableViewCellSeparatorStyleSingleLine UITableViewCellSeparatorStyleSingleLineEtched"),
		@"UITableViewCellStyle", _w(@"UITableViewCellStyleDefault UITableViewCellStyleValue1 UITableViewCellStyleValue2 UITableViewCellStyleSubtitle"),
		@"UITableViewRowAnimation", _w(@"UITableViewRowAnimationFade UITableViewRowAnimationRight UITableViewRowAnimationLeft UITableViewRowAnimationTop UITableViewRowAnimationBottom UITableViewRowAnimationNone UITableViewRowAnimationMiddle"),
		@"UITableViewScrollPosition", _w(@"UITableViewScrollPositionNone UITableViewScrollPositionTop UITableViewScrollPositionMiddle UITableViewScrollPositionBottom"),
		@"UITableViewStyle", _w(@"UITableViewStylePlain UITableViewStyleGrouped"),
		@"UITextAlignment", _w(@"UITextAlignmentLeft UITextAlignmentCenter UITextAlignmentRight"),
		@"UITextAutocapitalizationType", _w(@"UITextAutocapitalizationTypeNone UITextAutocapitalizationTypeWords UITextAutocapitalizationTypeSentences UITextAutocapitalizationTypeAllCharacters"),
		@"UITextAutocorrectionType", _w(@"UITextAutocorrectionTypeDefault UITextAutocorrectionTypeNo UITextAutocorrectionTypeYes"),
		@"UITextBorderStyle", _w(@"UITextBorderStyleNone UITextBorderStyleLine UITextBorderStyleBezel UITextBorderStyleRoundedRect"),
		@"UITextFieldViewMode", _w(@"UITextFieldViewModeNever UITextFieldViewModeWhileEditing UITextFieldViewModeUnlessEditing UITextFieldViewModeAlways"),
		@"UITextGranularity", _w(@"UITextGranularityCharacter UITextGranularityWord UITextGranularitySentence UITextGranularityParagraph UITextGranularityLine UITextGranularityDocument"),
		@"UITextLayoutDirection", _w(@"UITextLayoutDirectionRight UITextLayoutDirectionLeft UITextLayoutDirectionUp UITextLayoutDirectionDown"),
		@"UITextStorageDirection", _w(@"UITextStorageDirectionForward UITextStorageDirectionBackward"),
		@"UITextWritingDirection", _w(@"UITextWritingDirectionLeftToRight UITextWritingDirectionRightToLeft"),
		@"UITouchPhase", _w(@"UITouchPhaseBegan UITouchPhaseMoved UITouchPhaseStationary UITouchPhaseEnded UITouchPhaseCancelled"),
		@"UIUserInterfaceIdiom", _w(@"UIUserInterfaceIdiomPhone UIUserInterfaceIdiomPad"),
		@"UIViewAnimationCurve", _w(@"UIViewAnimationCurveEaseInOut UIViewAnimationCurveEaseIn UIViewAnimationCurveEaseOut UIViewAnimationCurveLinear"),
		@"UIViewAnimationTransition", _w(@"UIViewAnimationTransitionNone UIViewAnimationTransitionFlipFromLeft UIViewAnimationTransitionFlipFromRight UIViewAnimationTransitionCurlUp UIViewAnimationTransitionCurlDown"),
		@"UIViewContentMode", _w(@"UIViewContentModeScaleToFill UIViewContentModeScaleAspectFit UIViewContentModeScaleAspectFill UIViewContentModeRedraw UIViewContentModeCenter UIViewContentModeTop UIViewContentModeBottom UIViewContentModeLeft UIViewContentModeRight UIViewContentModeTopLeft UIViewContentModeTopRight UIViewContentModeBottomLeft UIViewContentModeBottomRight"),
	nil];
}

-(void) load_property_table {
	self.propertyTable = [NSDictionary dictionaryWithKeysAndObjects: 
		@"NSObject accessibilityFrame", @"CGRect",
		@"NSObject accessibilityTraits", @"UIAccessibilityTraits",
		@"NSObject isAccessibilityElement", @"BOOL",
		@"UIAcceleration timestamp", @"NSTimeInterval",
		@"UIAcceleration updateInterval", @"NSTimeInterval",
		@"UIAcceleration x", @"UIAccelerationValue",
		@"UIAcceleration y", @"UIAccelerationValue",
		@"UIAcceleration z", @"UIAccelerationValue",
		@"UIAccessibilityElement accessibilityFrame", @"CGRect",
		@"UIAccessibilityElement accessibilityTraits", @"UIAccessibilityTraits",
		@"UIAccessibilityElement isAccessibilityElement", @"BOOL",
		@"UIActionSheet actionSheetStyle", @"UIActionSheetStyle",
		@"UIActionSheet cancelButtonIndex", @"NSInteger",
		@"UIActionSheet destructiveButtonIndex", @"NSInteger",
		@"UIActionSheet firstOtherButtonIndex", @"NSInteger",
		@"UIActionSheet numberOfButtons", @"NSInteger",
		@"UIActionSheet visible", @"BOOL",
		@"UIActivityIndicatorView activityIndicatorViewStyle", @"UIActivityIndicatorViewStyle",
		@"UIActivityIndicatorView hidesWhenStopped", @"BOOL",
		@"UIAlertView cancelButtonIndex", @"NSInteger",
		@"UIAlertView firstOtherButtonIndex", @"NSInteger",
		@"UIAlertView numberOfButtons", @"NSInteger",
		@"UIAlertView visible", @"BOOL",
		@"UIApplication applicationIconBadgeNumber", @"NSInteger",
		@"UIApplication applicationState", @"UIApplicationState",
		@"UIApplication applicationSupportsShakeToEdit", @"BOOL",
		@"UIApplication backgroundTimeRemaining", @"NSTimeInterval",
		@"UIApplication idleTimerDisabled", @"BOOL",
		@"UIApplication networkActivityIndicatorVisible", @"BOOL",
		@"UIApplication protectedDataAvailable", @"BOOL",
		@"UIApplication proximitySensingEnabled", @"BOOL",
		@"UIApplication statusBarFrame", @"CGRect",
		@"UIApplication statusBarHidden", @"BOOL",
		@"UIApplication statusBarOrientation", @"UIInterfaceOrientation",
		@"UIApplication statusBarOrientationAnimationDuration", @"NSTimeInterval",
		@"UIApplication statusBarStyle", @"UIStatusBarStyle",
		@"UIBarButtonItem action", @"SEL",
		@"UIBarButtonItem style", @"UIBarButtonItemStyle",
		@"UIBarButtonItem width", @"CGFloat",
		@"UIBarItem enabled", @"BOOL",
		@"UIBarItem imageInsets", @"UIEdgeInsets",
		@"UIBarItem tag", @"NSInteger",
		@"UIBezierPath CGPath", @"CGPathRef",
		@"UIBezierPath bounds", @"CGRect",
		@"UIBezierPath currentPoint", @"CGPoint",
		@"UIBezierPath flatness", @"CGFloat",
		@"UIBezierPath lineCapStyle", @"CGLineCap",
		@"UIBezierPath lineJoinStyle", @"CGLineJoin",
		@"UIBezierPath lineWidth", @"CGFloat",
		@"UIBezierPath miterLimit", @"CGFloat",
		@"UIBezierPath usesEvenOddFillRule", @"BOOL",
		@"UIButton adjustsImageWhenDisabled", @"BOOL",
		@"UIButton adjustsImageWhenHighlighted", @"BOOL",
		@"UIButton buttonType", @"UIButtonType",
		@"UIButton contentEdgeInsets", @"UIEdgeInsets",
		@"UIButton imageEdgeInsets", @"UIEdgeInsets",
		@"UIButton lineBreakMode", @"UILineBreakMode",
		@"UIButton reversesTitleShadowWhenHighlighted", @"BOOL",
		@"UIButton showsTouchWhenHighlighted", @"BOOL",
		@"UIButton titleEdgeInsets", @"UIEdgeInsets",
		@"UIButton titleShadowOffset", @"CGSize",
		@"UIColor CGColor", @"CGColorRef",
		@"UIControl contentHorizontalAlignment", @"UIControlContentHorizontalAlignment",
		@"UIControl contentVerticalAlignment", @"UIControlContentVerticalAlignment",
		@"UIControl enabled", @"BOOL",
		@"UIControl highlighted", @"BOOL",
		@"UIControl selected", @"BOOL",
		@"UIControl state", @"UIControlState",
		@"UIControl touchInside", @"BOOL",
		@"UIControl tracking", @"BOOL",
		@"UIDatePicker countDownDuration", @"NSTimeInterval",
		@"UIDatePicker datePickerMode", @"UIDatePickerMode",
		@"UIDatePicker minuteInterval", @"NSInteger",
		@"UIDevice batteryLevel", @"float",
		@"UIDevice batteryMonitoringEnabled", @"BOOL",
		@"UIDevice batteryState", @"UIDeviceBatteryState",
		@"UIDevice enableInputClicksWhenVisible", @"BOOL",
		@"UIDevice generatesDeviceOrientationNotifications", @"BOOL",
		@"UIDevice multitaskingSupported", @"BOOL",
		@"UIDevice orientation", @"UIDeviceOrientation",
		@"UIDevice proximityMonitoringEnabled", @"BOOL",
		@"UIDevice proximityState", @"BOOL",
		@"UIDevice userInterfaceIdiom", @"UIUserInterfaceIdiom",
		@"UIEvent subtype", @"UIEventSubtype",
		@"UIEvent timestamp", @"NSTimeInterval",
		@"UIEvent type", @"UIEventType",
		@"UIFont ascender", @"CGFloat",
		@"UIFont capHeight", @"CGFloat",
		@"UIFont descender", @"CGFloat",
		@"UIFont leading", @"CGFloat",
		@"UIFont lineHeight", @"CGFloat",
		@"UIFont pointSize", @"CGFloat",
		@"UIFont xHeight", @"CGFloat",
		@"UIGestureRecognizer cancelsTouchesInView", @"BOOL",
		@"UIGestureRecognizer delaysTouchesBegan", @"BOOL",
		@"UIGestureRecognizer delaysTouchesEnded", @"BOOL",
		@"UIGestureRecognizer enabled", @"BOOL",
		@"UIGestureRecognizer state", @"UIGestureRecognizerState",
		@"UIImage CGImage", @"CGImageRef",
		@"UIImage imageOrientation", @"UIImageOrientation",
		@"UIImage leftCapWidth", @"NSInteger",
		@"UIImage scale", @"CGFloat",
		@"UIImage size", @"CGSize",
		@"UIImage topCapHeight", @"NSInteger",
		@"UIImagePickerController allowsEditing", @"BOOL",
		@"UIImagePickerController allowsImageEditing", @"BOOL",
		@"UIImagePickerController cameraCaptureMode", @"UIImagePickerControllerCameraCaptureMode",
		@"UIImagePickerController cameraDevice", @"UIImagePickerControllerCameraDevice",
		@"UIImagePickerController cameraFlashMode", @"UIImagePickerControllerCameraFlashMode",
		@"UIImagePickerController cameraViewTransform", @"CGAffineTransform",
		@"UIImagePickerController delegate", @"UIImagePickerControllerDelegate>",
		@"UIImagePickerController showsCameraControls", @"BOOL",
		@"UIImagePickerController sourceType", @"UIImagePickerControllerSourceType",
		@"UIImagePickerController videoMaximumDuration", @"NSTimeInterval",
		@"UIImagePickerController videoQuality", @"UIImagePickerControllerQualityType",
		@"UIImageView animationDuration", @"NSTimeInterval",
		@"UIImageView animationRepeatCount", @"NSInteger",
		@"UIImageView highlighted", @"BOOL",
		@"UIImageView userInteractionEnabled", @"BOOL",
		@"UILabel adjustsFontSizeToFitWidth", @"BOOL",
		@"UILabel baselineAdjustment", @"UIBaselineAdjustment",
		@"UILabel enabled", @"BOOL",
		@"UILabel highlighted", @"BOOL",
		@"UILabel lineBreakMode", @"UILineBreakMode",
		@"UILabel minimumFontSize", @"CGFloat",
		@"UILabel numberOfLines", @"NSInteger",
		@"UILabel shadowOffset", @"CGSize",
		@"UILabel textAlignment", @"UITextAlignment",
		@"UILabel userInteractionEnabled", @"BOOL",
		@"UILocalNotification applicationIconBadgeNumber", @"NSInteger",
		@"UILocalNotification hasAction", @"BOOL",
		@"UILocalNotification repeatInterval", @"NSCalendarUnit",
		@"UILongPressGestureRecognizer allowableMovement", @"CGFloat",
		@"UILongPressGestureRecognizer minimumPressDuration", @"CFTimeInterval",
		@"UILongPressGestureRecognizer numberOfTapsRequired", @"NSInteger",
		@"UILongPressGestureRecognizer numberOfTouchesRequired", @"NSInteger",
		@"UIMenuController action", @"SEL",
		@"UIMenuController arrowDirection", @"UIMenuControllerArrowDirection",
		@"UIMenuController menuFrame", @"CGRect",
		@"UIMenuController menuVisible", @"BOOL",
		@"UINavigationBar barStyle", @"UIBarStyle",
		@"UINavigationBar hidesBackButton", @"BOOL",
		@"UINavigationBar translucent", @"BOOL",
		@"UINavigationController hidesBottomBarWhenPushed", @"BOOL",
		@"UINavigationController navigationBarHidden", @"BOOL",
		@"UINavigationController toolbarHidden", @"BOOL",
		@"UIPageControl currentPage", @"NSInteger",
		@"UIPageControl defersCurrentPageDisplay", @"BOOL",
		@"UIPageControl hidesForSinglePage", @"BOOL",
		@"UIPageControl numberOfPages", @"NSInteger",
		@"UIPanGestureRecognizer maximumNumberOfTouches", @"NSUInteger",
		@"UIPanGestureRecognizer minimumNumberOfTouches", @"NSUInteger",
		@"UIPickerView numberOfComponents", @"NSInteger",
		@"UIPickerView showsSelectionIndicator", @"BOOL",
		@"UIPinchGestureRecognizer scale", @"CGFloat",
		@"UIPinchGestureRecognizer velocity", @"CGFloat",
		@"UIPopoverController contentSizeForViewInPopover", @"CGSize",
		@"UIPopoverController modalInPopover", @"BOOL",
		@"UIPopoverController popoverArrowDirection", @"UIPopoverArrowDirection",
		@"UIPopoverController popoverContentSize", @"CGSize",
		@"UIPopoverController popoverVisible", @"BOOL",
		@"UIPrintFormatter contentInsets", @"UIEdgeInsets",
		@"UIPrintFormatter maximumContentHeight", @"CGFloat",
		@"UIPrintFormatter maximumContentWidth", @"CGFloat",
		@"UIPrintFormatter pageCount", @"NSInteger",
		@"UIPrintFormatter startPage", @"NSInteger",
		@"UIPrintFormatter textAlignment", @"UITextAlignment",
		@"UIPrintInfo duplex", @"UIPrintInfoDuplex",
		@"UIPrintInfo orientation", @"UIPrintInfoOrientation",
		@"UIPrintInfo outputType", @"UIPrintInfoOutputType",
		@"UIPrintInteractionController showsPageRange", @"BOOL",
		@"UIPrintPageRenderer footerHeight", @"CGFloat",
		@"UIPrintPageRenderer headerHeight", @"CGFloat",
		@"UIPrintPageRenderer paperRect", @"CGRect",
		@"UIPrintPageRenderer printableRect", @"CGRect",
		@"UIProgressView progress", @"float",
		@"UIProgressView progressViewStyle", @"UIProgressViewStyle",
		@"UIRotationGestureRecognizer rotation", @"CGFloat",
		@"UIRotationGestureRecognizer velocity", @"CGFloat",
		@"UIScreen applicationFrame", @"CGRect",
		@"UIScreen bounds", @"CGRect",
		@"UIScreen scale", @"CGFloat",
		@"UIScrollView alwaysBounceHorizontal", @"BOOL",
		@"UIScrollView alwaysBounceVertical", @"BOOL",
		@"UIScrollView bounces", @"BOOL",
		@"UIScrollView bouncesZoom", @"BOOL",
		@"UIScrollView canCancelContentTouches", @"BOOL",
		@"UIScrollView contentInset", @"UIEdgeInsets",
		@"UIScrollView contentOffset", @"CGPoint",
		@"UIScrollView contentSize", @"CGSize",
		@"UIScrollView decelerating", @"BOOL",
		@"UIScrollView decelerationRate", @"float",
		@"UIScrollView delaysContentTouches", @"BOOL",
		@"UIScrollView directionalLockEnabled", @"BOOL",
		@"UIScrollView dragging", @"BOOL",
		@"UIScrollView indicatorStyle", @"UIScrollViewIndicatorStyle",
		@"UIScrollView maximumZoomScale", @"float",
		@"UIScrollView minimumZoomScale", @"float",
		@"UIScrollView pagingEnabled", @"BOOL",
		@"UIScrollView scrollEnabled", @"BOOL",
		@"UIScrollView scrollIndicatorInsets", @"UIEdgeInsets",
		@"UIScrollView scrollsToTop", @"BOOL",
		@"UIScrollView showsHorizontalScrollIndicator", @"BOOL",
		@"UIScrollView showsVerticalScrollIndicator", @"BOOL",
		@"UIScrollView tracking", @"BOOL",
		@"UIScrollView zoomBouncing", @"BOOL",
		@"UIScrollView zoomScale", @"float",
		@"UIScrollView zooming", @"BOOL",
		@"UISearchBar autocapitalizationType", @"UITextAutocapitalizationType",
		@"UISearchBar autocorrectionType", @"UITextAutocorrectionType",
		@"UISearchBar barStyle", @"UIBarStyle",
		@"UISearchBar keyboardType", @"UIKeyboardType",
		@"UISearchBar searchResultsButtonSelected", @"BOOL",
		@"UISearchBar selectedScopeButtonIndex", @"NSInteger",
		@"UISearchBar showsBookmarkButton", @"BOOL",
		@"UISearchBar showsCancelButton", @"BOOL",
		@"UISearchBar showsScopeBar", @"BOOL",
		@"UISearchBar showsSearchResultsButton", @"BOOL",
		@"UISearchBar translucent", @"BOOL",
		@"UISearchDisplayController active", @"BOOL",
		@"UISegmentedControl momentary", @"BOOL",
		@"UISegmentedControl numberOfSegments", @"NSUInteger",
		@"UISegmentedControl segmentedControlStyle", @"UISegmentedControlStyle",
		@"UISegmentedControl selectedSegmentIndex", @"NSInteger",
		@"UISlider continuous", @"BOOL",
		@"UISlider maximumValue", @"float",
		@"UISlider minimumValue", @"float",
		@"UISlider value", @"float",
		@"UISwipeGestureRecognizer direction", @"UISwipeGestureRecognizerDirection",
		@"UISwipeGestureRecognizer numberOfTouchesRequired", @"NSUInteger",
		@"UISwitch on", @"BOOL",
		@"UITabBarController selectedIndex", @"NSUInteger",
		@"UITableView allowsSelection", @"BOOL",
		@"UITableView allowsSelectionDuringEditing", @"BOOL",
		@"UITableView editing", @"BOOL",
		@"UITableView row", @"NSUInteger",
		@"UITableView rowHeight", @"CGFloat",
		@"UITableView section", @"NSUInteger",
		@"UITableView sectionFooterHeight", @"CGFloat",
		@"UITableView sectionHeaderHeight", @"CGFloat",
		@"UITableView sectionIndexMinimumDisplayRowCount", @"NSInteger",
		@"UITableView separatorStyle", @"UITableViewCellSeparatorStyle",
		@"UITableView style", @"UITableViewStyle",
		@"UITableViewCell accessoryAction", @"SEL",
		@"UITableViewCell accessoryType", @"UITableViewCellAccessoryType",
		@"UITableViewCell editAction", @"SEL",
		@"UITableViewCell editing", @"BOOL",
		@"UITableViewCell editingAccessoryType", @"UITableViewCellAccessoryType",
		@"UITableViewCell editingStyle", @"UITableViewCellEditingStyle",
		@"UITableViewCell hidesAccessoryWhenEditing", @"BOOL",
		@"UITableViewCell highlighted", @"BOOL",
		@"UITableViewCell indentationLevel", @"NSInteger",
		@"UITableViewCell indentationWidth", @"CGFloat",
		@"UITableViewCell lineBreakMode", @"UILineBreakMode",
		@"UITableViewCell selected", @"BOOL",
		@"UITableViewCell selectionStyle", @"UITableViewCellSelectionStyle",
		@"UITableViewCell shouldIndentWhileEditing", @"BOOL",
		@"UITableViewCell showingDeleteConfirmation", @"BOOL",
		@"UITableViewCell showsReorderControl", @"BOOL",
		@"UITableViewCell textAlignment", @"UITextAlignment",
		@"UITableViewController clearsSelectionOnViewWillAppear", @"BOOL",
		@"UITapGestureRecognizer numberOfTapsRequired", @"NSUInteger",
		@"UITapGestureRecognizer numberOfTouchesRequired", @"NSUInteger",
		@"UITextField adjustsFontSizeToFitWidth", @"BOOL",
		@"UITextField borderStyle", @"UITextBorderStyle",
		@"UITextField clearButtonMode", @"UITextFieldViewMode",
		@"UITextField clearsOnBeginEditing", @"BOOL",
		@"UITextField editing", @"BOOL",
		@"UITextField leftViewMode", @"UITextFieldViewMode",
		@"UITextField minimumFontSize", @"CGFloat",
		@"UITextField rightViewMode", @"UITextFieldViewMode",
		@"UITextField textAlignment", @"UITextAlignment",
		@"UITextPosition empty", @"BOOL",
		@"UITextView dataDetectorTypes", @"UIDataDetectorTypes",
		@"UITextView editable", @"BOOL",
		@"UITextView selectedRange", @"NSRange",
		@"UITextView textAlignment", @"UITextAlignment",
		@"UIToolbar barStyle", @"UIBarStyle",
		@"UIToolbar translucent", @"BOOL",
		@"UITouch phase", @"UITouchPhase",
		@"UITouch tapCount", @"NSUInteger",
		@"UITouch timestamp", @"NSTimeInterval",
		@"UIVideoEditorController delegate", @"UIVideoEditorControllerDelegate>",
		@"UIVideoEditorController videoMaximumDuration", @"NSTimeInterval",
		@"UIVideoEditorController videoQuality", @"UIImagePickerControllerQualityType",
		@"UIView alpha", @"CGFloat",
		@"UIView autoresizesSubviews", @"BOOL",
		@"UIView autoresizingMask", @"UIViewAutoresizing",
		@"UIView bounds", @"CGRect",
		@"UIView center", @"CGPoint",
		@"UIView clearsContextBeforeDrawing", @"BOOL",
		@"UIView clipsToBounds", @"BOOL",
		@"UIView contentMode", @"UIViewContentMode",
		@"UIView contentScaleFactor", @"CGFloat",
		@"UIView contentStretch", @"CGRect",
		@"UIView exclusiveTouch", @"BOOL",
		@"UIView frame", @"CGRect",
		@"UIView hidden", @"BOOL",
		@"UIView multipleTouchEnabled", @"BOOL",
		@"UIView opaque", @"BOOL",
		@"UIView tag", @"NSInteger",
		@"UIView transform", @"CGAffineTransform",
		@"UIView userInteractionEnabled", @"BOOL",
		@"UIViewController editing", @"BOOL",
		@"UIViewController interfaceOrientation", @"UIInterfaceOrientation",
		@"UIViewController modalPresentationStyle", @"UIModalPresentationStyle",
		@"UIViewController modalTransitionStyle", @"UIModalTransitionStyle",
		@"UIViewController wantsFullScreenLayout", @"BOOL",
		@"UIWebView allowsInlineMediaPlayback", @"BOOL",
		@"UIWebView canGoBack", @"BOOL",
		@"UIWebView canGoForward", @"BOOL",
		@"UIWebView dataDetectorTypes", @"UIDataDetectorTypes",
		@"UIWebView detectsPhoneNumbers", @"BOOL",
		@"UIWebView loading", @"BOOL",
		@"UIWebView mediaPlaybackRequiresUserAction", @"BOOL",
		@"UIWebView scalesPageToFit", @"BOOL",
		@"UIWindow keyWindow", @"BOOL",
		@"UIWindow windowLevel", @"UIWindowLevel",
	nil];
}

-(id) init {
	self = [super init];
	if (self) {
       [self load_typedef_table];
       [self load_property_table];
	}
	return self;
}

- (void)dealloc {
	[typedefTable release];
	[propertyTable release];
    [super dealloc];
}

@end

